export const PRODUCT_ASSIGN_SUPPLIER_REQUEST =
  "PRODUCT_ASSIGN_SUPPLIER_REQUEST";
export const PRODUCT_ASSIGN_SUPPLIER_SUCCESS =
  "PRODUCT_ASSIGN_SUPPLIER_SUCCESS";
export const PRODUCT_ASSIGN_SUPPLIER_FAIL = "PRODUCT_ASSIGN_SUPPLIER_FAIL";
export const PRODUCT_ASSIGN_SUPPLIER_RESET = "PRODUCT_ASSIGN_SUPPLIER_RESET";
